config/routes.rb
Ideaboard::Application.routes.draw do

  root to: 'welcome#index'
  get 'hello/(:name)' => 'welcome#hello'
  get 'ideas' => 'ideas#index'
  resources :ideas do
    member do
      post :upvote
      post :downvote
    end
  end

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :description, :name, :url, :votes
  validates :name, presence:true, length: {minimum:4} format: /^((?i)idea)[A-Z]/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.create(params[:idea])
    if @idea.save
      redirect_to ideas_path
    else
      render 'new'
    end
  end

  def upvote
    idea = Idea.find(params[:id])
    idea.votes = (idea.votes || 0) + 1
    idea.save
    redirect_to ideas_path
  end

  def downvote
    idea = Idea.find(params[:id])
    idea.votes = (idea.votes || 0) - 1
    idea.save
    redirect_to ideas_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def hello
    @name = params[:name] || 'Rails girls'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ideas/index.html.erb
<h1>List of Ideas</h1>
<table width="100%">
  <thead>
    <th>Like?</th>
    <th>Unlike?</th>
    <th>Idea Name</th>
    <th>Votes</th>
    <th>Description</th>
  </thead>
  <tbody>
      <% @ideas.each do |idea|%>
        <tr>
          <td>
            <%= button_to '&uarr;'.html_safe, upvote_idea_path(idea), method: :post, class: 'tiny button' %>
          </td>
          <td>
            <%= button_to '&darr;'.html_safe, downvote_idea_path(idea), method: :post, class: 'tiny button' %>
          </td>
          <td><%=idea.name%></td>
          <td><%=idea.votes%></td>
          <td><%=idea.description%></td>
        </tr>
      <%end%>
  </tbody>
</table>

app/views/ideas/new.html.erb
<% if @idea.errors.any? %>
  <% @idea.errors.full_messages.each do |msg|%>
    <div class = "alert-box alert">
      <%= msg %>
    </div>
  <% end %>
<%end%>
<h1>Create Ideas</h1>
<%= form_for(@idea) do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :votes%>
  <%= f.text_field :votes%>
  <%= f.label :description%>
  <%= f.text_area :description%>
  <%= f.submit class: 'button' %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/welcome/hello.html.erb
<h1>hello hjello rails</h1>
<h2>hello rails</h2>
<h3>hello rails</h3>
<p>hello <%= @name%>

app/views/welcome/index.html.erb
<h1>hello rails</h1>
<h2>hello rails</h2>
<h3>hello rails</h3>
<% 3.times do %>
<h4>inside times </h4>
<%end%>
<% [1,2,3,4].reverse.each do |i| %>
<h<%=i%>>this</h<%=i%>>
<%end%>